services:
  db:
    image: postgres:16-alpine
    container_name: mundobl-db
    environment:
      POSTGRES_USER: mundobl
      POSTGRES_PASSWORD: mundobl
      POSTGRES_DB: mundobl
    ports:
      - "5433:5432"
    volumes:
      - mundobl-data:/var/lib/postgresql/data

volumes:
  mundobl-data:
